# Generated by Django 5.0.3 on 2025-07-08 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('usuarios', '0002_alter_usuario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero_registro',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matarial_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('descripcion', models.TextField(max_length=255)),
                ('orden_compra', models.CharField(max_length=20)),
                ('numero_formulario', models.IntegerField(default=0)),
                ('unidad_manejo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateTimeField()),
                ('secretaria_flag', models.BooleanField(default=False)),
                ('unidad_flag', models.BooleanField(default=False)),
                ('oficina_flag', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo_unitario', models.FloatField(default=0)),
                ('costo_total', models.FloatField(blank=True, default=0, null=True)),
                ('factura', models.CharField(max_length=255)),
                ('estado_compra', models.CharField(default='PENDIENTE')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.oficinas')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='proveedor.proveedor')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.secretaria')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.unidad')),
                ('numero_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_compras.numero_registro')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_compras',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entrega', models.IntegerField(default=0)),
                ('estado_cardista', models.BooleanField(blank=True, null=True)),
                ('fecha_cardista', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('material_compras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_compras.matarial_compras')),
            ],
        ),
    ]
