# Generated by Django 5.0.3 on 2025-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_unitario',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
