# Generated by Django 5.0.3 on 2025-07-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_precio_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio_unitario',
            new_name='precio_total',
        ),
    ]
