# Generated by Django 5.0.3 on 2025-07-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_materiales_precio_paquete_materiales_precio_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='precio_paquete',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='precio_unidad',
        ),
    ]
