# Generated by Django 5.0.3 on 2025-07-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_materiales_precio_paquete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='codigo_paquete',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='color',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='tamaño',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='unidad_medida',
        ),
    ]
