# Generated by Django 5.0.3 on 2025-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_remove_materiales_codigo_paquete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo_clasificacion',
            field=models.CharField(error_messages={'unique': 'El codigo de la categoria ya existe'}, max_length=100, unique=True, verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='informacion_material',
            name='cantidad_paquete_unidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
