# Generated by Django 5.0.3 on 2025-07-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_categoria_codigo_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion_material',
            name='cantidad_paquete',
        ),
        migrations.AlterField(
            model_name='informacion_material',
            name='cantidad_paquete_unidad',
            field=models.IntegerField(verbose_name='unidad'),
        ),
    ]
