# Generated by Django 5.0.3 on 2025-07-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_remove_informacion_material_cantidad_paquete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion_material',
            name='precio_paquete',
        ),
        migrations.AlterField(
            model_name='informacion_material',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
