# Generated by Django 5.0.3 on 2025-07-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_remove_informacion_material_precio_paquete_and_more'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='informacion_material',
            name='factura',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacion_material',
            name='proveedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
            preserve_default=False,
        ),
    ]
