# Generated by Django 5.0.3 on 2025-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Presupuestos', 'Presupuestos'), ('Cardista', 'Kardixta'), ('Director_administrativo', 'Director Administrativo'), ('Encargado_oficina', 'Responsable de la oficina'), ('Usuario', 'Personal de la oficina')], default='Usuario', verbose_name='Encargado de unidad'),
        ),
    ]
